name: Konstantin Polyashenko
url: http://konopoly.github.io
files_url: http://files.konopoly.github.io
comments_url: http://comments.konopoly.github.io
description: Konstantin Polyashenko's personal site and blog.
permalink: /articles/:title
markdown: kramdown
lsi: true
exclude: [Gemfile, Gemfile.lock, nginx.conf, CNAME]
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true

sass:
  style: :compressed
