# Site settings
title: konopoly.github.io
description: Personal website of Konstantin Polyashenko
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Konstantin Polyashenko
user_description: Experienced software engineer with a passion for building amazing software. 
user_title: Software Engineer
email: kpolyash@gmail.com
github_username:  konopoly

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
